# Set working directory to include files from UCI HAR Datset

## General information 
labels <- read.table("./activity_labels.txt")
features <- read.table("./features.txt",colClasses=c("numeric","character"))

## Test set
test <- read.table("./test/X_test.txt",col.names=features$V2)
test_subj <- read.table("./test/subject_test.txt")
test_labels <- read.table("./test/y_test.txt")
test2 <- cbind(test_subj,test_labels,test)
colnames(test2)[1:2] <- c("subject","activity")

## Train set
train <- read.table("./train/X_train.txt",col.names=features$V2)
train_subj <- read.table("./train/subject_train.txt")
train_labels <- read.table("./train/y_train.txt")
train2 <- cbind(train_subj,train_labels,train)
colnames(train2)[1:2] <- c("subject","activity")

## Combine test and train sets
complete <- rbind(test2,train2)

complete2 <- subset(complete,
                    select=c("subject",
                             "activity",
                             "tBodyAcc.mean...X",
                             "tBodyAcc.mean...Y",
                             "tBodyAcc.mean...Z",
                             "tBodyAcc.std...X",
                             "tBodyAcc.std...Y",
                             "tBodyAcc.std...Z",
                             "tGravityAcc.mean...X",
                             "tGravityAcc.mean...Y",
                             "tGravityAcc.mean...Z",
                             "tGravityAcc.std...X",
                             "tGravityAcc.std...Y",
                             "tGravityAcc.std...Z",
                             "tBodyAccJerk.mean...X",
                             "tBodyAccJerk.mean...Y",
                             "tBodyAccJerk.mean...Z",
                             "tBodyAccJerk.std...X",
                             "tBodyAccJerk.std...Y",
                             "tBodyAccJerk.std...Z",
                             "tBodyGyro.mean...X",
                             "tBodyGyro.mean...Y",
                             "tBodyGyro.mean...Z",
                             "tBodyGyro.std...X",
                             "tBodyGyro.std...Y",
                             "tBodyGyro.std...Z",
                             "tBodyGyroJerk.mean...X",
                             "tBodyGyroJerk.mean...Y",
                             "tBodyGyroJerk.mean...Z",
                             "tBodyGyroJerk.std...X",
                             "tBodyGyroJerk.std...Y",
                             "tBodyGyroJerk.std...Z",
                             "tBodyAccMag.mean..",
                             "tBodyAccMag.std..",
                             "tGravityAccMag.mean..",
                             "tGravityAccMag.std..",
                             "tBodyAccJerkMag.mean..",
                             "tBodyAccJerkMag.std..",
                             "tBodyGyroMag.mean..",
                             "tBodyGyroMag.std..",
                             "tBodyGyroJerkMag.mean..",
                             "tBodyGyroJerkMag.std..",
                             "fBodyAcc.mean...X",
                             "fBodyAcc.mean...Y",
                             "fBodyAcc.mean...Z",
                             "fBodyAcc.std...X",
                             "fBodyAcc.std...Y",
                             "fBodyAcc.std...Z",
                             "fBodyAcc.meanFreq...X",
                             "fBodyAcc.meanFreq...Y",
                             "fBodyAcc.meanFreq...Z",
                             "fBodyAccJerk.mean...X",
                             "fBodyAccJerk.mean...Y",
                             "fBodyAccJerk.mean...Z",
                             "fBodyAccJerk.std...X",
                             "fBodyAccJerk.std...Y",
                             "fBodyAccJerk.std...Z",
                             "fBodyAccJerk.meanFreq...X",
                             "fBodyAccJerk.meanFreq...Y",
                             "fBodyAccJerk.meanFreq...Z",
                             "fBodyGyro.mean...X",
                             "fBodyGyro.mean...Y",
                             "fBodyGyro.mean...Z",
                             "fBodyGyro.std...X",
                             "fBodyGyro.std...Y",
                             "fBodyGyro.std...Z",
                             "fBodyGyro.meanFreq...X",
                             "fBodyGyro.meanFreq...Y",
                             "fBodyGyro.meanFreq...Z",
                             "fBodyAccMag.mean..",
                             "fBodyAccMag.std..",
                             "fBodyAccMag.meanFreq..",
                             "fBodyBodyAccJerkMag.mean..",
                             "fBodyBodyAccJerkMag.std..",
                             "fBodyBodyAccJerkMag.meanFreq..",
                             "fBodyBodyGyroMag.mean..",
                             "fBodyBodyGyroMag.std..",
                             "fBodyBodyGyroMag.meanFreq..",
                             "fBodyBodyGyroJerkMag.mean..",
                             "fBodyBodyGyroJerkMag.std..",
                             "fBodyBodyGyroJerkMag.meanFreq..",
                             "angle.tBodyAccMean.gravity.",
                             "angle.tBodyAccJerkMean..gravityMean.",
                             "angle.tBodyGyroMean.gravityMean.",
                             "angle.tBodyGyroJerkMean.gravityMean.",
                             "angle.X.gravityMean.",
                             "angle.Y.gravityMean.",
                             "angle.Z.gravityMean."))

## Rename activity factor levels
complete2$activity <- as.factor(complete2$activity)
levels(complete2$activity) <- as.character(labels$V2)

## Rename variables descriptively.
colnames(complete2) <- c("Subject", "Activity",
                         "BodyAcceleration.X.mean",
                         "BodyAcceleration.Y.mean",
                         "BodyAcceleration.Z.mean",
                         "BodyAcceleration.X.std",
                         "BodyAcceleration.Y.std",
                         "BodyAcceleration.Z.std",
                         "GravityAcceleration.X.mean",
                         "GravityAcceleration.Y.mean",
                         "GravityAcceleration.Z.mean",
                         "GravityAcceleration.X.std",
                         "GravityAcceleration.Y.std",
                         "GravityAcceleration.Z.std",
                         "BodyAccelerationJerk.X.mean",
                         "BodyAccelerationJerk.Y.mean",
                         "BodyAccelerationJerk.Z.mean",
                         "BodyAccelerationJerk.X.std",
                         "BodyAccelerationJerk.Y.std",
                         "BodyAccelerationJerk.Z.std",
                         "BodyGyroscope.X.mean",
                         "BodyGyroscope.Y.mean",
                         "BodyGyroscope.Z.mean",
                         "BodyGyroscope.X.std",
                         "BodyGyroscope.Y.std",
                         "BodyGyroscope.Z.std",
                         "BodyGyroscopeJerk.X.mean",
                         "BodyGyroscopeJerk.Y.mean",
                         "BodyGyroscopeJerk.Z.mean",
                         "BodyGyroscopeJerk.X.std",
                         "BodyGyroscopeJerk.Y.std",
                         "BodyGyroscopeJerk.Z.std",
                         "BodyAccelerationMagnitude.mean",
                         "BodyAccelerationMagnitude.std",
                         "GravityAccelerationMagnitude.mean",
                         "GravityAccelerationMagnitude.std",
                         "BodyAccelerationJerkMagnitude.mean",
                         "BodyAccelerationJerkMagnitude.std",
                         "BodyGyroscopeMagnitude.mean",
                         "BodyGyroscopeMagnitude.std",
                         "BodyGyroscopeJerkMagnitude.mean",
                         "BodyGyroscopeJerkMagnitude.std",
                         "FreqBodyAcceleration.X.mean",
                         "FreqBodyAcceleration.Y.mean",
                         "FreqBodyAcceleration.Z.mean",
                         "FreqBodyAcceleration.X.std",
                         "FreqBodyAcceleration.Y.std",
                         "FreqBodyAcceleration.Z.std",
                         "MeanFreqBodyAcceleration.X",
                         "MeanFreqBodyAcceleration.Y",
                         "MeanFreqBodyAcceleration.Z",
                         "FreqBodyAccelerationJerk.X.mean",
                         "FreqBodyAccelerationJerk.Y.mean",
                         "FreqBodyAccelerationJerk.Z.mean",
                         "FreqBodyAccelerationJerk.X.std",
                         "FreqBodyAccelerationJerk.Y.std",
                         "FreqBodyAccelerationJerk.Z.std",
                         "MeanFreqBodyAccelerationJerk.X",
                         "MeanFreqBodyAccelerationJerk.Y",
                         "MeanFreqBodyAccelerationJerk.Z",
                         "FreqBodyGyroscope.X.mean",
                         "FreqBodyGyroscope.Y.mean",
                         "FreqBodyGyroscope.Z.mean",
                         "FreqBodyGyroscope.X.std",
                         "FreqBodyGyroscope.Y.std",
                         "FreqBodyGyroscope.Z.std",
                         "MeanFreqBodyGyroscope.X",
                         "MeanFreqBodyGyroscope.Y",
                         "MeanFreqBodyGyroscope.Z",
                         "FreqBodyAccelerationMagnitude.mean",
                         "FreqBodyAccelerationMagnitude.std",
                         "MeanFreqBodyAccelerationMagnitude",
                         "FreqBodyAccelerationJerkMagnitude.mean",
                         "FreqBodyAccelerationJerkMagnitude.std",
                         "MeanFreqBodyAccelerationJerkMagnitude",
                         "FreqBodyGyroscopeMagnitude.mean",
                         "FreqBodyGyroscopeMagnitude.std",
                         "MeanFreqBodyGyroscopeMagnitude",
                         "FreqBodyGyroscopeJerkMagnitude.mean",
                         "FreqBodyGyroscopeJerkMagnitude.std",
                         "MeanFreqBodyGyroscopeJerkMagnitude",
                         "AngleMeanBodyAcceleration.Gravity",
                         "AngleMeanBodyAcceleration.GravityMean",
                         "AngleMeanBodyGyroscope.GravityMean",
                         "AngleMeanBodyGyroscopeJerk.GravityMean",
                         "Angle.GravityMean.X",
                         "Angle.GravityMean.Y",
                         "Angle.GravityMean.Z")

## Take average of each variable for each activity and each subject.
final <- aggregate(. ~ Subject + Activity, data=complete2, FUN=mean)
write.table(final,"./project_data.txt",row.names=FALSE)
